name: flutter_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  dio: any
  retrofit: any
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^3.0.4
  path_provider: ^2.0.2
  hive: any
  hive_flutter: any
  get_it: any
  injectable: any
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.4.0
  ffi: any
  flutter_easyloading: any
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  flutter_staggered_animations: ^1.1.1
  modal_bottom_sheet: ^3.0.0
  getwidget: ^4.0.0

dev_dependencies:
  ffigen: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: any
  injectable_generator: any
  drift_dev: ^2.16.0
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
